apiVersion: v1
kind: Service
metadata:
    name: gamutkart-service
    labels:
      app: gamutkart-app

spec:
  selector:
    app: gamutkart-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
